sonar.projectKey=codnect_tag
sonar.organization=codnect
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go coverage
sonar.go.coverage.reportPaths=../../coverage.out